title: David Alber
url: https://www.davidalber.net
description: David Alber's blog.

image_base:  "/images"
date_format: "%b %-d, %Y"

header_pages:
 - about.md

permalink:    /:categories/:year/:month/:title/

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-feed
paginate:     10
sass:
  compressed: true

exclude: ["Rakefile", "Gemfile", "Gemfile.lock", "make-tag-files.sh", "blog.org"]

compress_html:
  comments: ["<!-- ", " -->"]
#  ignore:
#    envs: [dev]

repository: "davidalber/davidalber.github.io"
